### ISSUE TITLE
ServiceNow git integration broken

### ISSUE THREAD

**Issue by johncaruso** [phifogg/now_siamlight#10]
Your last commit (adding CONTRIBUTING.md) invalidated checksum.txt, so (after forking), this repo can no longer be imported into ServiceNow. I was able to workaround by cloning the repo to my local PC and doing the following:
```
git revert c6fd2497708de003250243518924392a58449578
git push
```
I would suggest reverting your last commit so others are able to fork and import into their instances without issue.

Thanks very much for this contribution to the community! Something like this really needs to be incorporated into the base product.

**Comment by phifogg** [comment]
Hi John,
I could submit without any issue. Can you check again?
Thanks,
Daniel

**Comment by johncaruso** [comment]
I'm not sure what you mean by "I could submit without any issue." 

If you want to verify the repo is now broken, try commiting a change from your ServiceNow instance. You should get the following error: `checksum.txt either is missing or contains an invalid checksum. Ensure your repository contains a valid, unmodified source image exported by an instance`

If you want to see the error other people are now getting when attempting to import a fork of your repo, try forking and then importing into your instance the repo I just created - an empty scoped app but with a new file added outside of my instance (directly via GitHub): `https://github.com/johncaruso/gittest`

If you read the README.md that ServiceNow adds to repos it integrates with you will see the following:

> This repository contains generated files and a checksum.
> 
> **Do not edit the files in this repository outside of an instance of ServiceNow.**

When you added the CONTRIBUTING.md to your repo, you did so "outside an instance of ServiceNow" and therefore invalidated the checksum.txt file that ServiceNow uses to ensure that the repo can only be changed via an instance.

**Comment by phifogg** [comment]
Commit is what I meant by submit :)
I just committed a minor update from my instance without issue.

**Comment by phifogg** [comment]
Ok, had the same isssue now with the next commit... I see. Will fix it shortly.

**Comment by phifogg** [comment]
Took me way to long to fix this. Sorry about it. But repo is now up and green again.
