### ISSUE TITLE
Because "Process Input Entry" BR is ASYNC no Referenced Record ID is returned

### ISSUE THREAD

**Issue by timharris777** [phifogg/now_siamlight#4]
Hi, because the "Process Input Entry" BR is ASYNC when the response gets returned to whoever is inserting a record there is no value in the referenced record field. How is the person sending the message supposed to get a unique id for the new ticket to correlate back? THanks!

**Comment by phifogg** [comment]
Hi Tim, this is correct. The idea with the queue table is to be asnychronous and therefor be able to respond very quick to an incoming message. But yes, this response is basically just an acknowledgement, nothing about the processing. Two options if you need the feedback to the 3rd party system:
a) Create an outbound trigger on the records that is being inserted to send a more ore less immediate feedback - this will work if the 3rd party can relate the information back to its originating call. You would be able to send their ID which they have send initially.
b) Create a scripted web service that would receive the data - same structure as table API on the queue table. This web service would simply forward the entry to the queue and trigger the process directly. I can post an example of that if you need one, did that for one of my customers.

**Comment by cnavr** [comment]
Hi Daniel, I have done the option a) as you suggested. I populated external ID into the custom field in Incident table but the outbound trigger  set on insert did not sent this external ID value (though other fields sys_id, incidentNUM ... were sent). It seems like it is populated not in initial insert but in immediate update. Any idea why and how to resolve that? Thanks. Ctirad

**Comment by phifogg** [comment]
Hi Ctirad,
you will not need to populate the external id in a custom field for that. SIAM will keep track of it in the table 'External ID' (x_snc_siam_light_external_id) if you tell it to. In the field map you can mark one field as 'unqiue id'. This way it knows which payload content is to be stored as unique id.
The same works on outbound, if set the unique ID tickbox it will go and fetch it from the external ID table.
Other than that, I would not see a reason why this is not stored on initial insert. Can you check the history of the incident record to see if there are two updates/saves happening? It should not.
Daniel

**Comment by cnavr** [comment]
Hi Daniel,
we need to keep external ID in specific Incident field, since the design requires it. 
Regarding the incident creation. When I look into the history  of the incident it shows Update number 0 and 1 in same second.  So it looks like the incident is updated. Ctirad

**Comment by timharris777** [comment]
I'll see if I can work on extending this via my Fork. I'll post an update here once I have a solution packaged within the app.

**Comment by phifogg** [comment]
Ok, if you need the external ID in a incident field you can map it twice in the field map. This does work just fine.

If you see a second update happening, please check the BR's running on the target tables. I would think that something else is updating it a second time. This should not happen.

**Comment by timharris777** [comment]
I have not worked on snow for over three years. Closing this issue.
